node {
    docker.image('node:lts-buster-slim').withRun('-p 3000:3000') { c ->
        try {
            env.CI = 'true'
            
            stage('Build') {
                steps {
                    sh 'npm install'
                }
            }
            
            stage('Test') {
                steps {
                    sh './jenkins/scripts/test.sh'
                }
            }
            
           
        } 
    }
}
